"""
Configuración Constructora Adille
Fuente: Control_de_Obras_Marzo_2026.xlsx
"""

CONFIG = {
    "nombre_empresa": "Constructora Adille",
    "slug": "adille",
    "color_filament": "amber",

    "tablas": {

        "obras": {
            "label": "Obras",
            "label_singular": "Obra",
            "primary_key": "id",
            "primary_key_type": "bigint",
            "columnas_tabla": ["nombre", "responsable", "fecha_inicio", "fecha_plazo", "estado", "avance_pct", "cobrado", "total_gastado", "resultado"],
            "campos": {
                "nombre":        {"tipo": "string",  "editable": True,  "label": "Obra",           "rules": "required|max:100"},
                "responsable":   {"tipo": "string",  "editable": True,  "label": "Responsable"},
                "fecha_inicio":  {"tipo": "date",    "editable": True,  "label": "Inicio",          "rules": "nullable|date"},
                "fecha_plazo":   {"tipo": "date",    "editable": True,  "label": "Plazo",           "rules": "nullable|date"},
                "dias_restantes":{"tipo": "integer", "editable": False, "label": "Días restantes [AUTO]", "auto": True},
                "estado":        {"tipo": "enum",    "editable": True,  "label": "Estado",
                                  "opciones": ["En curso", "Atrasada", "Completada", "Pausada"],
                                  "rules": "required|in:En curso,Atrasada,Completada,Pausada"},
                "avance_pct":    {"tipo": "decimal", "editable": True,  "label": "Avance %",       "rules": "nullable|numeric|min:0|max:100"},
                "cobrado":       {"tipo": "integer", "editable": False, "label": "Cobrado ($) [AUTO]",    "auto": True},
                "materiales":    {"tipo": "integer", "editable": False, "label": "Materiales ($) [AUTO]", "auto": True},
                "mano_obra":     {"tipo": "integer", "editable": False, "label": "Mano obra ($) [AUTO]",  "auto": True},
                "otros":         {"tipo": "integer", "editable": False, "label": "Otros ($) [AUTO]",      "auto": True},
                "total_gastado": {"tipo": "integer", "editable": False, "label": "Total gastado ($) [AUTO]", "auto": True},
                "resultado":     {"tipo": "integer", "editable": False, "label": "Resultado ($) [AUTO]",  "auto": True},
                "margen":        {"tipo": "decimal", "editable": False, "label": "Margen [AUTO]",         "auto": True},
                "problema_riesgo":{"tipo":"text",    "editable": True,  "label": "Problema/Riesgo"},
            },
            "observer_formulas": {
                "dias_restantes": r"($model->fecha_plazo) ? (int)\Carbon\Carbon::today()->diffInDays($model->fecha_plazo, false) : 0",
                "cobrado":        r"\App\Models\Facturacion::where('obra_id', $model->id)->sum('monto_cobrado')",
                "materiales":     r"\App\Models\Material::where('obra_id', $model->id)->sum('costo')",
                "mano_obra":      r"\App\Models\Liquidacion::where('obra_id', $model->id)->sum('a_pagar')",
                "otros":          r"\App\Models\BencinaTransporte::where('obra_id', $model->id)->sum('total')",
                "total_gastado":  r"($model->materiales ?? 0) + ($model->mano_obra ?? 0) + ($model->otros ?? 0)",
                "resultado":      r"($model->cobrado ?? 0) - ($model->total_gastado ?? 0)",
                "margen":         r"($model->cobrado > 0) ? round($model->resultado / $model->cobrado, 4) : 0",
            },
        },

        "materiales": {
            "label": "Control de Materiales",
            "label_singular": "Material",
            "primary_key": "id",
            "primary_key_type": "bigint",
            "columnas_tabla": ["obra_id", "fecha", "detalle", "costo", "tiene_iva"],
            "campos": {
                "obra_id":   {"tipo": "integer", "editable": True,  "label": "Obra",          "rules": "required|exists:obras,id"},
                "fecha":     {"tipo": "date",    "editable": True,  "label": "Fecha",         "rules": "required|date"},
                "detalle":   {"tipo": "string",  "editable": True,  "label": "Detalle",       "rules": "required|max:200"},
                "costo":     {"tipo": "integer", "editable": True,  "label": "Costo ($)",     "rules": "required|integer|min:0"},
                "tiene_iva": {"tipo": "boolean", "editable": True,  "label": "IVA incluido"},
                "proveedor": {"tipo": "string",  "editable": True,  "label": "Proveedor"},
                "boleta_num":{"tipo": "string",  "editable": True,  "label": "N° Boleta/Factura"},
                "notas":     {"tipo": "text",    "editable": True,  "label": "Notas"},
            },
            "observer_formulas": {},
        },

        "personal": {
            "label": "Control de Personal",
            "label_singular": "Trabajador",
            "primary_key": "id",
            "primary_key_type": "bigint",
            "columnas_tabla": ["codigo", "obra", "trabajador", "sueldo_base", "dias_laborales", "dias_trabajados", "faltas", "a_pagar"],
            "campos": {
                "codigo":          {"tipo": "string",  "editable": True,  "label": "Código",          "rules": "required|max:20"},
                "obra":            {"tipo": "string",  "editable": True,  "label": "Obra",            "rules": "required|max:100"},
                "trabajador":      {"tipo": "string",  "editable": True,  "label": "Trabajador",      "rules": "required|max:100"},
                "sueldo_base":     {"tipo": "integer", "editable": True,  "label": "Sueldo base ($)", "rules": "required|integer|min:0"},
                "dias_laborales":  {"tipo": "integer", "editable": True,  "label": "Días laborales",  "rules": "required|integer|min:1|max:31"},
                "dias_trabajados": {"tipo": "integer", "editable": True,  "label": "Días trabajados", "rules": "required|integer|min:0"},
                "faltas":          {"tipo": "integer", "editable": False, "label": "Faltas [AUTO]",   "auto": True},
                "valor_dia":       {"tipo": "integer", "editable": False, "label": "Valor día ($) [AUTO]",         "auto": True},
                "descuento_faltas":{"tipo": "integer", "editable": False, "label": "Descuento faltas ($) [AUTO]",  "auto": True},
                "a_pagar":         {"tipo": "integer", "editable": False, "label": "A pagar ($) [AUTO]",           "auto": True},
                "quincena_pagada": {"tipo": "integer", "editable": True,  "label": "Quincena pagada ($)"},
                "saldo":           {"tipo": "integer", "editable": False, "label": "Saldo ($) [AUTO]",             "auto": True},
                "mes":             {"tipo": "string",  "editable": True,  "label": "Mes"},
            },
            "observer_formulas": {
                "faltas":           r"max(0, ($model->dias_laborales ?? 0) - ($model->dias_trabajados ?? 0))",
                "valor_dia":        r"($model->dias_laborales > 0) ? (int)round($model->sueldo_base / $model->dias_laborales) : 0",
                "descuento_faltas": r"($model->valor_dia ?? 0) * ($model->faltas ?? 0)",
                "a_pagar":          r"($model->sueldo_base ?? 0) - ($model->descuento_faltas ?? 0)",
                "saldo":            r"($model->a_pagar ?? 0) - ($model->quincena_pagada ?? 0)",
            },
        },

        "facturacion": {
            "label": "Facturación",
            "label_singular": "Factura",
            "primary_key": "id",
            "primary_key_type": "bigint",
            "columnas_tabla": ["obra_id", "mes", "monto_cobrado", "tipo_cobro", "fecha_cobro"],
            "campos": {
                "obra_id":      {"tipo": "integer", "editable": True,  "label": "Obra",          "rules": "required"},
                "mes":          {"tipo": "string",  "editable": True,  "label": "Mes",           "rules": "required|max:20"},
                "monto_cobrado":{"tipo": "integer", "editable": True,  "label": "Monto cobrado ($)", "rules": "required|integer|min:0"},
                "ppm":          {"tipo": "decimal", "editable": False, "label": "PPM [AUTO]",    "auto": True},
                "tipo_cobro":   {"tipo": "enum",    "editable": True,  "label": "Tipo cobro",
                                 "opciones": ["Factura", "Boleta", "Transferencia", "Otro"]},
                "fecha_cobro":  {"tipo": "date",    "editable": True,  "label": "Fecha cobro"},
                "notas":        {"tipo": "text",    "editable": True,  "label": "Notas"},
            },
            "observer_formulas": {
                "ppm": r"round($model->monto_cobrado * 0.025252, 2)",
            },
        },

        "bencina_transporte": {
            "label": "Bencina y Transporte",
            "label_singular": "Gasto transporte",
            "primary_key": "id",
            "primary_key_type": "bigint",
            "columnas_tabla": ["obra_id", "fecha", "tipo", "monto", "total"],
            "campos": {
                "obra_id":          {"tipo": "integer", "editable": True,  "label": "Obra",                "rules": "required"},
                "fecha":            {"tipo": "date",    "editable": True,  "label": "Fecha",               "rules": "required|date"},
                "tipo":             {"tipo": "enum",    "editable": True,  "label": "Tipo",
                                     "opciones": ["Bencina camioneta", "Bencina auto", "Transporte trabajadores"]},
                "monto":            {"tipo": "integer", "editable": True,  "label": "Monto ($)",           "rules": "required|integer|min:0"},
                "total":            {"tipo": "integer", "editable": False, "label": "Total acumulado [AUTO]", "auto": True},
                "detalle":          {"tipo": "string",  "editable": True,  "label": "Detalle"},
            },
            "observer_formulas": {
                "total": r"\App\Models\BencinaTransporte::where('obra_id', $model->obra_id)->sum('monto')",
            },
        },
    },

    "kpis": [
        {
            "id": "resultado_total",
            "label": "Resultado global",
            "descripcion": "Cobrado menos gastado en todas las obras",
            "icono": "heroicon-o-scale",
            "color": "info",
            "query": r"'$'.number_format(\App\Models\Obra::sum('cobrado') - \App\Models\Obra::sum('total_gastado'), 0, ',', '.')",
        },
        {
            "id": "obras_activas",
            "label": "Obras activas",
            "descripcion": "Obras en curso actualmente",
            "icono": "heroicon-o-building-office-2",
            "color": "primary",
            "query": r"\App\Models\Obra::whereIn('estado', ['En curso', 'Atrasada'])->count().' obras'",
        },
        {
            "id": "gasto_materiales",
            "label": "Gasto materiales",
            "descripcion": "Total materiales todas las obras",
            "icono": "heroicon-o-cube",
            "color": "warning",
            "query": r"'$'.number_format(\App\Models\Material::sum('costo'), 0, ',', '.')",
        },
        {
            "id": "gasto_personal",
            "label": "Costo personal",
            "descripcion": "Total liquidaciones a pagar",
            "icono": "heroicon-o-users",
            "color": "danger",
            "query": r"'$'.number_format(\App\Models\Personal::sum('a_pagar'), 0, ',', '.')",
        },
        {
            "id": "cobrado_total",
            "label": "Total cobrado",
            "descripcion": "Suma de todas las facturas cobradas",
            "icono": "heroicon-o-banknotes",
            "color": "success",
            "query": r"'$'.number_format(\App\Models\Facturacion::sum('monto_cobrado'), 0, ',', '.')",
        },
        {
            "id": "obras_atrasadas",
            "label": "Obras atrasadas",
            "descripcion": "Obras con días restantes negativos",
            "icono": "heroicon-o-exclamation-triangle",
            "color": "danger",
            "query": r"\App\Models\Obra::where('estado', 'Atrasada')->count().' obras'",
        },
    ],
}
