"""
Configuración KraftDo SpA — BD v4
Fuente: KraftDo_BD_v4.xlsx
"""

CONFIG = {
    "nombre_empresa": "KraftDo SpA",
    "slug": "kraftdo",
    "color_filament": "violet",

    "tablas": {

        "productos": {
            "label": "Productos",
            "label_singular": "Producto",
            "primary_key": "sku",
            "primary_key_type": "string",
            "columnas_tabla": ["sku", "categoria", "nombre", "costo_total", "margen", "precio_unit", "precio_mayor", "estado"],
            "campos": {
                "sku":            {"tipo": "string",  "editable": True,  "label": "SKU",              "rules": "required|max:20|unique:productos,sku"},
                "categoria":      {"tipo": "string",  "editable": True,  "label": "Categoría"},
                "nombre":         {"tipo": "string",  "editable": True,  "label": "Nombre",            "rules": "required|max:100"},
                "variante":       {"tipo": "string",  "editable": True,  "label": "Variante"},
                "costo_insumo":   {"tipo": "integer", "editable": True,  "label": "Costo insumo ($)",  "rules": "required|integer|min:0"},
                "costo_produccion":{"tipo":"integer", "editable": True,  "label": "Costo producción ($)","rules": "required|integer|min:0"},
                "costo_total":    {"tipo": "integer", "editable": False, "label": "Costo total ($)",   "auto": True},
                "margen":         {"tipo": "decimal", "editable": True,  "label": "Margen (0-1)",      "rules": "required|numeric|min:0|max:0.99"},
                "precio_unit":    {"tipo": "integer", "editable": False, "label": "Precio unit. ($)",  "auto": True},
                "precio_mayor":   {"tipo": "integer", "editable": False, "label": "Precio mayor. ($)", "auto": True},
                "stock":          {"tipo": "integer", "editable": True,  "label": "Stock"},
                "dias_produccion":{"tipo": "integer", "editable": True,  "label": "Días producción"},
                "estado":         {"tipo": "enum",    "editable": True,  "label": "Estado",
                                   "opciones": ["Activo", "Inactivo", "Descontinuado"],
                                   "rules": "required|in:Activo,Inactivo,Descontinuado"},
                "proveedor_id":   {"tipo": "string",  "editable": True,  "label": "ID Proveedor"},
                "notas":          {"tipo": "text",    "editable": True,  "label": "Notas"},
                "gramos_3d":      {"tipo": "decimal", "editable": True,  "label": "Gramos 3D"},
                "horas_3d":       {"tipo": "decimal", "editable": True,  "label": "Horas 3D"},
                "nivel_digital":  {"tipo": "string",  "editable": True,  "label": "Nivel digital"},
            },
            "observer_formulas": {
                "costo_total":  "($model->costo_insumo ?? 0) + ($model->costo_produccion ?? 0)",
                "precio_unit":  "($model->margen > 0 && $model->margen < 1) ? (int)round(($model->costo_insumo + $model->costo_produccion) / (1 - $model->margen)) : ($model->costo_insumo + $model->costo_produccion)",
                "precio_mayor": "(int)round($model->precio_unit * 0.895)",
            },
        },

        "clientes": {
            "label": "Clientes",
            "label_singular": "Cliente",
            "primary_key": "id_cliente",
            "primary_key_type": "string",
            "columnas_tabla": ["id_cliente", "nombre_empresa", "tipo", "ciudad", "rubro", "canal_origen"],
            "campos": {
                "id_cliente":           {"tipo": "string", "editable": True,  "label": "ID Cliente",     "rules": "required|max:20|unique:clientes,id_cliente"},
                "nombre_empresa":       {"tipo": "string", "editable": True,  "label": "Nombre/Empresa", "rules": "required|max:120"},
                "tipo":                 {"tipo": "enum",   "editable": True,  "label": "Tipo",
                                         "opciones": ["Empresa", "Colegio", "Persona", "Municipio", "Otro"],
                                         "rules": "nullable|in:Empresa,Colegio,Persona,Municipio,Otro"},
                "whatsapp":             {"tipo": "string", "editable": True,  "label": "WhatsApp"},
                "ciudad":               {"tipo": "string", "editable": True,  "label": "Ciudad"},
                "correo":               {"tipo": "string", "editable": True,  "label": "Correo",         "rules": "nullable|email"},
                "rubro":                {"tipo": "string", "editable": True,  "label": "Rubro"},
                "canal_origen":         {"tipo": "string", "editable": True,  "label": "Canal origen"},
                "fecha_primer_contacto":{"tipo": "date",   "editable": True,  "label": "Primer contacto"},
                "observaciones":        {"tipo": "text",   "editable": True,  "label": "Observaciones"},
            },
            "observer_formulas": {},
        },

        "pedidos": {
            "label": "Pedidos",
            "label_singular": "Pedido",
            "primary_key": "id_pedido",
            "primary_key_type": "string",
            "columnas_tabla": ["id_pedido", "fecha", "nombre_cliente", "sku", "cantidad", "precio_unit_calc", "total", "ganancia", "margen_pct", "estado"],
            "campos": {
                "id_pedido":       {"tipo": "string",  "editable": True,  "label": "ID Pedido",        "rules": "required|max:30"},
                "fecha":           {"tipo": "date",    "editable": True,  "label": "Fecha",             "rules": "required|date"},
                "id_cliente":      {"tipo": "string",  "editable": True,  "label": "ID Cliente",        "rules": "required"},
                "nombre_cliente":  {"tipo": "string",  "editable": False, "label": "Cliente [AUTO]",    "auto": True},
                "sku":             {"tipo": "string",  "editable": True,  "label": "SKU Producto",      "rules": "required"},
                "producto":        {"tipo": "string",  "editable": False, "label": "Producto [AUTO]",   "auto": True},
                "cantidad":        {"tipo": "integer", "editable": True,  "label": "Cantidad",          "rules": "required|integer|min:1"},
                "precio_unit_calc":{"tipo": "integer", "editable": False, "label": "Precio unit. ($) [AUTO-volumen]", "auto": True},
                "costo_unit":      {"tipo": "integer", "editable": False, "label": "Costo unit. ($) [AUTO]",          "auto": True},
                "total":           {"tipo": "integer", "editable": False, "label": "Total ($) [AUTO]",               "auto": True},
                "ganancia":        {"tipo": "integer", "editable": False, "label": "Ganancia ($) [AUTO]",            "auto": True},
                "margen_pct":      {"tipo": "decimal", "editable": False, "label": "Margen % [AUTO]",               "auto": True},
                "anticipo":        {"tipo": "integer", "editable": False, "label": "Anticipo 50% [AUTO]",           "auto": True},
                "saldo":           {"tipo": "integer", "editable": False, "label": "Saldo [AUTO]",                  "auto": True},
                "fecha_entrega":   {"tipo": "date",    "editable": True,  "label": "F. Entrega"},
                "estado":          {"tipo": "enum",    "editable": True,  "label": "Estado",
                                    "opciones": ["Pendiente", "En producción", "Listo", "Entregado", "Confirmado", "Cancelado"],
                                    "rules": "required|in:Pendiente,En producción,Listo,Entregado,Confirmado,Cancelado"},
                "canal":           {"tipo": "string",  "editable": True,  "label": "Canal"},
                "registrado_por":  {"tipo": "string",  "editable": True,  "label": "Registrado por"},
                "observaciones":   {"tipo": "text",    "editable": True,  "label": "Observaciones"},
            },
            "observer_formulas": {
                "nombre_cliente":   r"optional(\App\Models\Cliente::where('id_cliente', $model->id_cliente)->first())->nombre_empresa ?? ''",
                "producto":         r"optional(\App\Models\Producto::where('sku', $model->sku)->first())->nombre ?? ''",
                "costo_unit":       r"optional(\App\Models\Producto::where('sku', $model->sku)->first())->costo_total ?? 0",
                "precio_unit_calc": r"(function() use ($model) { $p = \App\Models\Producto::where('sku', $model->sku)->first(); if (!$p) return 0; return ($model->cantidad >= 15) ? $p->precio_mayor : $p->precio_unit; })()",
                "total":            r"($model->precio_unit_calc ?? 0) * ($model->cantidad ?? 0)",
                "ganancia":         r"($model->total ?? 0) - (($model->costo_unit ?? 0) * ($model->cantidad ?? 0))",
                "margen_pct":       r"($model->total > 0) ? round($model->ganancia / $model->total, 4) : 0",
                "anticipo":         r"(int)round(($model->total ?? 0) * 0.5)",
                "saldo":            r"($model->total ?? 0) - ($model->anticipo ?? 0)",
            },
        },

        "caja": {
            "label": "Caja",
            "label_singular": "Movimiento",
            "primary_key": "id",
            "primary_key_type": "bigint",
            "columnas_tabla": ["id", "fecha", "tipo", "subcategoria", "monto", "saldo", "proveedor_cliente", "concepto"],
            "campos": {
                "numero":          {"tipo": "integer", "editable": False, "label": "N° [AUTO]",           "auto": True},
                "fecha":           {"tipo": "date",    "editable": True,  "label": "Fecha",               "rules": "required|date"},
                "tipo":            {"tipo": "enum",    "editable": True,  "label": "Tipo",
                                    "opciones": ["Ingreso", "Egreso"],
                                    "rules": "required|in:Ingreso,Egreso"},
                "subcategoria":    {"tipo": "enum",    "editable": True,  "label": "Subcategoría",
                                    "opciones": ["Venta producto", "Anticipo recibido", "Saldo recibido", "Gasto fijo", "Insumo", "Otro ingreso", "Otro egreso"],
                                    "rules": "required"},
                "monto":           {"tipo": "integer", "editable": True,  "label": "Monto ($)",           "rules": "required|integer|min:1"},
                "saldo":           {"tipo": "integer", "editable": False, "label": "Saldo ($) [AUTO]",    "auto": True},
                "id_pedido":       {"tipo": "string",  "editable": True,  "label": "ID Pedido"},
                "proveedor_cliente":{"tipo":"string",  "editable": True,  "label": "Proveedor/Cliente"},
                "concepto":        {"tipo": "string",  "editable": True,  "label": "Concepto",            "rules": "required|max:200"},
                "registrado_por":  {"tipo": "string",  "editable": True,  "label": "Registrado por"},
            },
            "observer_formulas": {
                "saldo": r"(function() use ($model) { $anterior = \App\Models\Caja::where('id', '<', $model->id)->orderBy('id', 'desc')->value('saldo') ?? 0; return $anterior + (($model->tipo === 'Ingreso') ? $model->monto : -$model->monto); })()",
            },
        },

        "insumos": {
            "label": "Insumos",
            "label_singular": "Insumo",
            "primary_key": "id_insumo",
            "primary_key_type": "string",
            "columnas_tabla": ["id_insumo", "nombre", "unidad", "stock_actual", "stock_minimo", "alerta_stock", "costo_unitario"],
            "campos": {
                "id_insumo":     {"tipo": "string",  "editable": True,  "label": "ID Insumo",       "rules": "required|max:20|unique:insumos,id_insumo"},
                "nombre":        {"tipo": "string",  "editable": True,  "label": "Nombre",          "rules": "required|max:100"},
                "unidad":        {"tipo": "string",  "editable": True,  "label": "Unidad"},
                "stock_actual":  {"tipo": "integer", "editable": True,  "label": "Stock actual",    "rules": "nullable|integer|min:0"},
                "stock_minimo":  {"tipo": "integer", "editable": True,  "label": "Stock mínimo",    "rules": "nullable|integer|min:0"},
                "alerta_stock":  {"tipo": "string",  "editable": False, "label": "Alerta [AUTO]",   "auto": True},
                "costo_unitario":{"tipo": "integer", "editable": True,  "label": "Costo unit. ($)", "rules": "nullable|integer|min:0"},
                "proveedor_id":  {"tipo": "string",  "editable": True,  "label": "ID Proveedor"},
                "notas":         {"tipo": "text",    "editable": True,  "label": "Notas"},
            },
            "observer_formulas": {
                "alerta_stock": r"($model->stock_actual <= $model->stock_minimo) ? '⚠️ REPONER' : '✅ OK'",
            },
        },

        "proveedores": {
            "label": "Proveedores",
            "label_singular": "Proveedor",
            "primary_key": "id_proveedor",
            "primary_key_type": "string",
            "columnas_tabla": ["id_proveedor", "nombre", "tipo", "despacho_vi_region", "minimo_compra"],
            "campos": {
                "id_proveedor":      {"tipo": "string",  "editable": True, "label": "ID Proveedor",     "rules": "required|max:20|unique:proveedores,id_proveedor"},
                "nombre":            {"tipo": "string",  "editable": True, "label": "Nombre",           "rules": "required|max:100"},
                "sitio_web":         {"tipo": "string",  "editable": True, "label": "Sitio web/Contacto"},
                "tipo":              {"tipo": "string",  "editable": True, "label": "Tipo"},
                "despacho_vi_region":{"tipo": "boolean", "editable": True, "label": "Despacho VI Región"},
                "minimo_compra":     {"tipo": "integer", "editable": True, "label": "Mínimo compra ($)"},
                "envio_gratis":      {"tipo": "string",  "editable": True, "label": "Condición envío gratis"},
                "notas":             {"tipo": "text",    "editable": True, "label": "Notas"},
            },
            "observer_formulas": {},
        },
    },

    "kpis": [
        {
            "id": "ventas_mes",
            "label": "Ventas del mes",
            "descripcion": "Total facturado en el mes actual",
            "icono": "heroicon-o-banknotes",
            "color": "success",
            "query": r"'$'.number_format(\App\Models\Pedido::whereMonth('fecha', now()->month)->whereYear('fecha', now()->year)->sum('total'), 0, ',', '.')",
        },
        {
            "id": "pedidos_activos",
            "label": "Pedidos activos",
            "descripcion": "En producción o pendientes",
            "icono": "heroicon-o-clipboard-document-list",
            "color": "warning",
            "query": r"\App\Models\Pedido::whereIn('estado', ['Pendiente', 'En producción', 'Confirmado'])->count().' pedidos'",
        },
        {
            "id": "saldo_caja",
            "label": "Saldo en caja",
            "descripcion": "Saldo actual del libro de caja",
            "icono": "heroicon-o-currency-dollar",
            "color": "info",
            "query": r"'$'.number_format(\App\Models\Caja::latest('id')->value('saldo') ?? 0, 0, ',', '.')",
        },
        {
            "id": "stock_critico",
            "label": "Insumos críticos",
            "descripcion": "Insumos bajo stock mínimo",
            "icono": "heroicon-o-exclamation-triangle",
            "color": "danger",
            "query": r"\App\Models\Insumo::whereColumn('stock_actual', '<=', 'stock_minimo')->count().' insumos'",
        },
        {
            "id": "ganancia_mes",
            "label": "Ganancia del mes",
            "descripcion": "Ganancia neta pedidos del mes",
            "icono": "heroicon-o-arrow-trending-up",
            "color": "success",
            "query": r"'$'.number_format(\App\Models\Pedido::whereMonth('fecha', now()->month)->whereYear('fecha', now()->year)->sum('ganancia'), 0, ',', '.')",
        },
        {
            "id": "productos_activos",
            "label": "Productos activos",
            "descripcion": "Productos en catálogo activo",
            "icono": "heroicon-o-squares-2x2",
            "color": "primary",
            "query": r"\App\Models\Producto::where('estado', 'Activo')->count().' productos'",
        },
    ],
}
